<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'apihelpers' => '/../lib/APIHelpers.class.php',
                'assetshelper' => '/../lib/Helpers/Assets.php',
                'autotable' => '/../lib/MODxAPI/autoTable.abstract.php',
                'content_dl_filter' => '/../snippets/DocLister/core/filter/content.filter.php',
                'dlcollection' => '/../snippets/DocLister/lib/DLCollection.class.php',
                'dldebug' => '/../snippets/DocLister/lib/DLdebug.class.php',
                'dlfixedprepare' => '/../snippets/DocLister/lib/DLFixedPrepare.class.php',
                'dlpaginate' => '/../snippets/DocLister/lib/DLpaginate.class.php',
                'dlphx' => '/../snippets/DocLister/lib/DLphx.class.php',
                'dlreflect' => '/../snippets/DocLister/lib/DLReflect.class.php',
                'dltemplate' => '/../snippets/DocLister/lib/DLTemplate.class.php',
                'dlusers\\actions' => '/../snippets/DLUsers/src/Actions.php',
                'doclister' => '/../snippets/DocLister/core/DocLister.abstract.php',
                'e_dl_extender' => '/../snippets/DocLister/core/extender/e.extender.php',
                'example_dl_extender' => '/../snippets/DocLister/core/extender/example.extender.php',
                'extdoclister' => '/../snippets/DocLister/core/extDocLister.abstract.php',
                'filterdoclister' => '/../snippets/DocLister/core/filterDocLister.abstract.php',
                'formatter\\htmlformatter' => '/../lib/Formatter/HtmlFormatter.php',
                'formatter\\sqlformatter' => '/../lib/Formatter/SqlFormatter.php',
                'helpers\\collection' => '/../lib/Helpers/Collection.php',
                'helpers\\fs' => '/../lib/Helpers/FS.php',
                'helpers\\phpthumb' => '/../lib/Helpers/PHPThumb.php',
                'helpers\\video' => '/../lib/Helpers/Video.php',
                'jotcount_dl_extender' => '/../snippets/DocLister/core/extender/jotcount.extender.php',
                'jsonhelper' => '/../snippets/DocLister/lib/jsonHelper.class.php',
                'modcategories' => '/../lib/MODxAPI/modCategories.php',
                'modchunk' => '/../lib/MODxAPI/modChunk.php',
                'modmodule' => '/../lib/MODxAPI/modModule.php',
                'modplugin' => '/../lib/MODxAPI/modPlugin.php',
                'modresource' => '/../lib/MODxAPI/modResource.php',
                'modsnippet' => '/../lib/MODxAPI/modSnippet.php',
                'modtemplate' => '/../lib/MODxAPI/modTemplate.php',
                'modtv' => '/../lib/MODxAPI/modTV.php',
                'module\\action' => '/../lib/Module/Action.php',
                'module\\helper' => '/../lib/Module/Helper.php',
                'module\\template' => '/../lib/Module/Template.php',
                'modusers' => '/../lib/MODxAPI/modUsers.php',
                'modxapi' => '/../lib/MODxAPI/MODx.php',
                'modxapihelpers' => '/../lib/MODxAPI/MODx.php',
                'onetabledoclister' => '/../snippets/DocLister/core/controller/onetable.php',
                'paginate_dl_extender' => '/../snippets/DocLister/core/extender/paginate.extender.php',
                'prepare_dl_extender' => '/../snippets/DocLister/core/extender/prepare.extender.php',
                'private_dl_filter' => '/../snippets/DocLister/core/filter/private.filter.php',
                'request_dl_extender' => '/../snippets/DocLister/core/extender/request.extender.php',
                'shopkeeperdoclister' => '/../snippets/DocLister/core/controller/shopkeeper.php',
                'simpletab\\abstractcontroller' => '/../lib/SimpleTab/controller.abstract.php',
                'simpletab\\datatable' => '/../lib/SimpleTab/table.abstract.php',
                'simpletab\\plugin' => '/../lib/SimpleTab/plugin.class.php',
                'site_content_filtersdoclister' => '/../snippets/DocLister/core/controller/site_content_filters.php',
                'site_content_tagsdoclister' => '/../snippets/DocLister/core/controller/site_content_tags.php',
                'site_contentdoclister' => '/../snippets/DocLister/core/controller/site_content.php',
                'sqlhelper' => '/../snippets/DocLister/lib/sqlHelper.class.php',
                'summary_dl_extender' => '/../snippets/DocLister/core/extender/summary.extender.php',
                'summarytext' => '/../lib/class.summary.php',
                'template_dl_extender' => '/../snippets/DocLister/core/extender/template.extender.php',
                'tv_dl_extender' => '/../snippets/DocLister/core/extender/tv.extender.php',
                'tv_dl_filter' => '/../snippets/DocLister/core/filter/tv.filter.php',
                'tvd_dl_filter' => '/../snippets/DocLister/core/filter/tvd.filter.php',
                'user_dl_extender' => '/../snippets/DocLister/core/extender/user.extender.php',
                'xnop' => '/../snippets/DocLister/lib/xnop.class.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
